vich_uploader:
    db_driver: orm
    mappings:
        player_images:
            uri_prefix: /images/players
            upload_destination: '%kernel.project_dir%/public/images/players'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        article_images:
            uri_prefix: /images/articles
            upload_destination: '%kernel.project_dir%/public/images/articles'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true